# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:32:27+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class AWSAccountId(RootModel[constr(pattern=r'[0-9]{12}')]):
    root: constr(pattern=r'[0-9]{12}')


class AccessDeniedException(RootModel[Any]):
    root: Any


class AssociateMemberAccountRequest(BaseModel):
    memberAccountId: AWSAccountId


class BucketName(RootModel[constr(max_length=500)]):
    root: constr(max_length=500)


class DisassociateMemberAccountRequest(BaseModel):
    memberAccountId: AWSAccountId


class ErrorCode(RootModel[constr(max_length=10)]):
    root: constr(max_length=10) = Field(..., description='Error code for the exception')


class ExceptionMessage(RootModel[constr(max_length=10000)]):
    root: constr(max_length=10000)


class InternalException(RootModel[Any]):
    root: Any


class InvalidInputException(RootModel[Any]):
    root: Any


class LimitExceededException(RootModel[Any]):
    root: Any


class MaxResults(RootModel[conint(le=250)]):
    root: conint(le=250)


class MemberAccount(BaseModel):
    accountId: Optional[AWSAccountId] = None


class MemberAccounts(RootModel[List[MemberAccount]]):
    root: List[MemberAccount]


class NextToken(RootModel[constr(max_length=500)]):
    root: constr(max_length=500)


class Prefix(RootModel[constr(max_length=10000)]):
    root: constr(max_length=10000)


class S3ContinuousClassificationType(Enum):
    FULL = 'FULL'


class S3OneTimeClassificationType(Enum):
    FULL = 'FULL'
    NONE = 'NONE'


class S3Resource(BaseModel):
    bucketName: BucketName
    prefix: Optional[Prefix] = None


class S3Resources(RootModel[List[S3Resource]]):
    root: List[S3Resource]


class XAmzTarget(Enum):
    MacieService_AssociateMemberAccount = 'MacieService.AssociateMemberAccount'


class XAmzTarget1(Enum):
    MacieService_AssociateS3Resources = 'MacieService.AssociateS3Resources'


class XAmzTarget2(Enum):
    MacieService_DisassociateMemberAccount = 'MacieService.DisassociateMemberAccount'


class XAmzTarget3(Enum):
    MacieService_DisassociateS3Resources = 'MacieService.DisassociateS3Resources'


class XAmzTarget4(Enum):
    MacieService_ListMemberAccounts = 'MacieService.ListMemberAccounts'


class XAmzTarget5(Enum):
    MacieService_ListS3Resources = 'MacieService.ListS3Resources'


class XAmzTarget6(Enum):
    MacieService_UpdateS3Resources = 'MacieService.UpdateS3Resources'


class ClassificationType(BaseModel):
    continuous: S3ContinuousClassificationType
    oneTime: S3OneTimeClassificationType


class ClassificationTypeUpdate(BaseModel):
    continuous: Optional[S3ContinuousClassificationType] = None
    oneTime: Optional[S3OneTimeClassificationType] = None


class DisassociateS3ResourcesRequest(BaseModel):
    associatedS3Resources: S3Resources
    memberAccountId: Optional[AWSAccountId] = None


class FailedS3Resource(BaseModel):
    errorCode: Optional[ErrorCode] = None
    errorMessage: Optional[ExceptionMessage] = None
    failedItem: Optional[S3Resource] = None


class FailedS3Resources(RootModel[List[FailedS3Resource]]):
    root: List[FailedS3Resource]


class ListMemberAccountsRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[NextToken] = None


class ListMemberAccountsResult(BaseModel):
    memberAccounts: Optional[MemberAccounts] = None
    nextToken: Optional[NextToken] = None


class ListS3ResourcesRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    memberAccountId: Optional[AWSAccountId] = None
    nextToken: Optional[NextToken] = None


class S3ResourceClassification(BaseModel):
    bucketName: BucketName
    classificationType: ClassificationType
    prefix: Optional[Prefix] = None


class S3ResourceClassificationUpdate(BaseModel):
    bucketName: BucketName
    classificationTypeUpdate: ClassificationTypeUpdate
    prefix: Optional[Prefix] = None


class S3ResourcesClassification(RootModel[List[S3ResourceClassification]]):
    root: List[S3ResourceClassification]


class S3ResourcesClassificationUpdate(RootModel[List[S3ResourceClassificationUpdate]]):
    root: List[S3ResourceClassificationUpdate]


class UpdateS3ResourcesRequest(BaseModel):
    memberAccountId: Optional[AWSAccountId] = None
    s3ResourcesUpdate: S3ResourcesClassificationUpdate


class UpdateS3ResourcesResult(BaseModel):
    failedS3Resources: Optional[FailedS3Resources] = None


class AssociateS3ResourcesRequest(BaseModel):
    memberAccountId: Optional[AWSAccountId] = None
    s3Resources: S3ResourcesClassification


class AssociateS3ResourcesResult(BaseModel):
    failedS3Resources: Optional[FailedS3Resources] = None


class DisassociateS3ResourcesResult(BaseModel):
    failedS3Resources: Optional[FailedS3Resources] = None


class ListS3ResourcesResult(BaseModel):
    nextToken: Optional[NextToken] = None
    s3Resources: Optional[S3ResourcesClassification] = None
